language: ruby
env:
  - TRAVIS=true
branches:
  only:
    - 'master'
rvm:
  - 1.9.3-p327
  - 2.0.0
before_script:
  - "cp config.yml.example config.yml"
  - "touch authorized_keys"
script: "bundle exec rspec spec"

